version: "3"
services:
  db:
    image: mysql:5.7
    ports:
      - "5076:3306"
    volumes:
      - ./conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./mysql/:/var/lib/mysql/:rw
    # env_file: .env-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "blog"
      MYSQL_USER: "blog"
      MYSQL_PASSWORD: "123456789"

  web:
    build: .
    volumes:
      - ".:/code"
    ports:
      - "8008:8000" # 端口暴露（主机端口:容器端口）
    # command: django-admin startproject mysite .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
