"""
Django settings for leif_im project.

Generated by 'django-admin startproject' using Django 2.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from collections import OrderedDict

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'w3k)a^#fd@rvlc*ec)&+2glmsor785(g8*lj1m@-ad48dh%3sm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'apps.blog',
    'pagedown',
    'compressor',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.blog.context_processors.theme',
            ],
        },
    },
]

WSGI_APPLICATION = 'wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 10
}

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

COMPRESS_ENABLED = True

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'collectstatic')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
)

SITE_ID = 1

# ---------------------------------------------------------------
# 主题配置
# ---------------------------------------------------------------
SITE_TITLE = "Leif.余炜纹"
SITE_SUBTITLE = "我纹身抽烟喝酒说脏话、但我知道我是好姑娘"
KEYWORDS = "Leif, Php, Python, Go, React, Vue.js"

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------
MENU = OrderedDict(
    sorted(
        {
            "home": {"label": "首页", "path": "/", "icon": "home", "position": 1},
            "categories": {"label": "分类", "path": "/categories", "icon": "th", "position": 3},
            "archives": {"label": "归档", "path": "/archives", "icon": "archive", "position": 2},
            "tags": {"label": "标签", "path": "/tags", "icon": "tags", "position": 4},
            "about": {"label": "关于", "path": "/about", "icon": "user", "position": 5},
        }.items(),
        key=lambda t: t[1]['position']
    )
)

SCHEME = "Pisces"

SOCIAL = OrderedDict(
    sorted(
        {
            "GitHub": {"label": u"GitHub", "link": "https://github.com/yuleicc", "social_icons": "github", "position": 1},
            "Twitter": {"label": u"Twitter", "link": "https://twitter.com/leif_yulei", "social_icons": "twitter", "position": 2},
            "Weibo": {"label": u"微博", "link": "http://weibo.com/yuleicc ", "social_icons": "weibo", "position": 3},
            "Zhihu": {"label": u"知乎", "link": "https://www.zhihu.com/people/yulei-323", "social_icons": "", "position": 5},
        }.items(),
        key=lambda t: t[1]['position'])
)

USE_MOTION = True
RSS = '/rss'
FAVICON = 'favicon.png'
VERSION = '1.0.0'
ALIPAY = ""
WECHATPAY = ""
