# Generated by Django 2.1.1 on 2018-10-03 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('title', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='标题')),
                ('slug', models.SlugField(blank=True, default='no-slug', max_length=160)),
                ('cover', models.URLField(blank=True, default='', verbose_name='封面')),
                ('snippet', models.CharField(default='', max_length=500, verbose_name='摘要')),
                ('content', models.TextField(verbose_name='内容')),
                ('publish_time', models.DateTimeField(null=True, verbose_name='发表时间')),
                ('status', models.CharField(choices=[('d', '草稿'), ('p', '已发布')], default='d', max_length=1, verbose_name='状态')),
                ('is_public', models.BooleanField(default=True, verbose_name='公开')),
                ('is_top', models.BooleanField(default=False, verbose_name='置顶')),
                ('access_count', models.IntegerField(default=1, editable=False, verbose_name='浏览量')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='名称')),
                ('slug', models.SlugField(blank=True, default='no-slug', max_length=160)),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='图标')),
                ('type', models.CharField(blank=True, max_length=64, null=True, verbose_name='类型')),
                ('is_show', models.BooleanField(choices=[(0, 'NR - 不显示'), (1, 'R - 显示')], default=0, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='名称')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='标签', to='blog.Tag', verbose_name='标签集合'),
        ),
    ]
